services:
  - type: web
    name: apg-marketing-portal
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: API_KEY
        sync: false # Debes a√±adir tu API Key en el dashboard de Render