services:
  - type: web
    name: apg-marketing-portal
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist

    # Reglas necesarias para SPA con React + Vite
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

    envVars:
      - key: API_KEY
        sync: false
