
services:
  - type: web
    name: apg-marketing-portal
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: API_KEY
        sync: false
      - key: AIRTABLE_PAT
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false
      - key: AIRTABLE_TABLE_ID
        sync: false
